name: quadtree
version: 0.1.0
description: A simple quadtree implementation in Dart.
homepage: https://arkaung.github.io/quadtree
repository: https://github.com/arkaung/quadtree

environment:
  sdk: ^3.5.0

dependencies:

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
